### ISSUE TITLE
Nullability annotations?

### ISSUE THREAD

**Issue by nolanw** [firebase/geofire-objc#105]
Hello! If I opened a pull request that annotated all the public headers with `nonnull`/`nullable`, how likely is it that it would be accepted? I wouldn't mind getting rid of all the `!`s when using GeoFire from Swift, but I'm not sure I want to maintain a nullability fork and deal with merge conflicts down the line.

**Comment by morganchen12** [comment]
I'd be happy to review your pull request.

**Comment by mcdonamp** [comment]
Published in v2.0.1.
