### ISSUE TITLE
Framework not found Metal

### ISSUE THREAD

**Issue by marcllucia** [firebase/geofire-objc#11]
Trying to compile the new framework version the following error appears: 

```ld: framework not found Metal for architecture armv7````

Doing some research I think you should add the "-weak_framework Metal" linker flag when building the library.

**Comment by jwngr** [comment]
Hey @marcllucia, sorry for never responding to this - it must have just fell through the cracks. Were you able to get this solved? If not, I'm sure @jdimond can take a look at it since he has the most knowledge here.

**Comment by jdimond** [comment]
I think this is unrelated to GeoFire. Are you trying to use GeoFire with some other Framework?
