### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by kennyray** [firebase/geofire-objc#113]
I just tried to run the IOS sample code and it doesn't even compile.

**Comment by RadiBarq** [comment]
could you give us the error code or the compilation error you have.

**Comment by kennyray** [comment]
Sorry, I don't recall what the error was. I've moved on to other projects now. If I ever run into this issue again I'll be sure to put more details. Not sure why I didn't add them back in April. 😐

**Comment by RadiBarq** [comment]
no worries

**Comment by yanndupuy** [comment]
Hi, i run in the same issue.

It seems code sample wasn't update and dont compile.

If we run pod install and then try compile 'GeoFire' workspace we get the following error : 

`
Showing Recent Messages
:-1: Multiple commands produce '/Users/yanndupuy/Library/Developer/Xcode/DerivedData/GeoFire-boevceiikxsdilcdxqijcwefphna/Build/Products/Debug-iphonesimulator/include/GeoFire/GeoFire.h':
1) Target 'GeoFire' (project 'GeoFire') has copy command from '/Users/yanndupuy/Documents/0-zyapps/0-projects/0-zyapps/Savane/3-AppCodeSample/0-App-CodeSample/geofire-objc-master/GeoFire/API/GeoFire.h' to '/Users/yanndupuy/Library/Developer/Xcode/DerivedData/GeoFire-boevceiikxsdilcdxqijcwefphna/Build/Products/Debug-iphonesimulator/include/GeoFire/GeoFire.h'
2) Target 'GeoFire' (project 'GeoFire') has copy command from '/Users/yanndupuy/Documents/0-zyapps/0-projects/0-zyapps/Savane/3-AppCodeSample/0-App-CodeSample/geofire-objc-master/GeoFire/API/GeoFire.h' to '/Users/yanndupuy/Library/Developer/Xcode/DerivedData/GeoFire-boevceiikxsdilcdxqijcwefphna/Build/Products/Debug-iphonesimulator/include/GeoFire/GeoFire.h'
`
If we remove in build phases copy files entry "GeoFire.h" that compile

However if we try to launch scheme 'Framework' For compile we need modify workspace settings for use Legacy build system and not new build system which generate an error ( XCode > File > Workspace Settings). There is also many warnings on project settings (deployment, etc)

After fix this issues i try to compile example project 'SFVehicles' however every time i get an error for 'lib-Pods-GeoFire.a' not found

'
Showing Recent Messages
:-1: Build input file cannot be found: '/Users/yanndupuy/Library/Developer/Xcode/DerivedData/SFVehicles-cieywshotjjcagbqgvfxonsrrqqf/Build/Products/Debug-iphoneos/libPods-GeoFire.a'
'

It would be great to get an updated code sample for test this framework.

Regards

**Comment by morganchen12** [comment]
This is fixed in 4781cf005a3740cbe371507b8b09d08db4840088.
