### ISSUE TITLE
Installing GeoFire with Firebase Database 6.3

### ISSUE THREAD

**Issue by SchnMar** [firebase/geofire-objc#124]
[!] CocoaPods could not find compatible versions for pod "Firebase/Database":
  In snapshot (Podfile.lock):
    Firebase/Database (= 6.3.0)

  In Podfile:
    Firebase/Database

    GeoFire (~> 3.0) was resolved to 3.0.0, which depends on
      Firebase/Database (~> 5.0)

Specs satisfying the `Firebase/Database, Firebase/Database (= 6.3.0), Firebase/Database (~> 5.0)` dependency were found, but they required a higher minimum deployment target.

Can someone help me with this? I'm rookie in regard to Swift programming!

**Comment by morganchen12** [comment]
You need to increase the version of your minimum deployment target (the oldest version of iOS supported by your app) to at least iOS 8.0.

**Comment by samgermaindeveloper** [comment]
@morganchen12  Can you give an example of how to do this?
