### ISSUE TITLE
What is the Pricing logic for Geo Queries?

### ISSUE THREAD

**Issue by aytunch** [firebase/geofire-objc#132]
Let's say I have 100,000 locations saved in the DB. And I make a radius query which returns 5 locations. Will I be charged for 100,000 document reads or 5? In the background do we download the unused results too?

Also while listening to a query result in real time, If a location changes which is out of bounds of my query, does that still count as a read?

**Comment by morganchen12** [comment]
The answer is the same as the one provided by Sam here: https://github.com/firebase/geofire-java/issues/162
