### ISSUE TITLE
ready event not triggered 

### ISSUE THREAD

**Issue by pgherveou** [firebase/geofire-objc#16]
Hey guys, thanks for this cool lib

I noticed the following by using your module in my swift app
- the ready event is triggered the first time
- then if I change my center or radius and this does not trigger any enter exit event, the ready event is not triggered again

my current workaround is to remove and reassign my ready observer
Sorry, I am not super fluent with objc so its hard to investigate your code any further

**Comment by jdimond** [comment]
This does look like a bug. We'll look into it...

**Comment by pgherveou** [comment]
Cool, can you let us know when the new pod is released!

**Comment by jwngr** [comment]
Yup, we will definitely let you know.

**Comment by jwngr** [comment]
Version 1.1.2 of the GeoFire Cocoapod has been released with a fix for this issue ([change log](https://github.com/firebase/geofire-objc/releases/tag/v1.1.2), [Cocoapods](https://cocoapods.org/?q=geofire)).Thanks for alerting us of this issue!

**Comment by pgherveou** [comment]
Thks for fixing it ;)
