### ISSUE TITLE
Does NOT work with latest Firebase (Firebase 9.0.0). 

### ISSUE THREAD

**Issue by colincavil112** [firebase/geofire-objc#161]
Please update the library to work with Firebase 9.0.0 or please provide a way to use GeoFire from within the Firebase frameworks..

**Comment by snoop168** [comment]
Any chance this will be updated to work with firebase 9.x?

**Comment by rebeloper** [comment]
Would love to see this resolved as soon as possible. Thank you

**Comment by rebeloper** [comment]
Ended up using: https://github.com/emilioschepis/swift-geohash.git

**Comment by abdoelmorap** [comment]
just use this 

pod 'GeoFire', :git => 'https://github.com/abdoelmorap/geofire-objc', :tag => '5.4.0'

**Comment by strohat** [comment]
This is such a well developed solution - hope support can come back to it.

**Comment by cantonalex** [comment]
> at your Podfile use this and everything will work fine pod 'GeoFire', :git => 'https://github.com/abdoelmorap/geofire-objc', :tag => '5.4.0'

does this actually work @abdoelmorap

**Comment by morganchen12** [comment]
This is now fixed.
