### ISSUE TITLE
Need to know wether still being maintained? Current dependency constrains to < 9.0.0 and Firebase > 10.0

### ISSUE THREAD

**Issue by kennedycraig** [firebase/geofire-objc#162]
Folks, it would be good to have some kind of answer as to whether this is being maintained or whether we need to look for another solution. This solution is constrained to a version of Firebase which is now outdated. Could you please advise?

**Comment by smaldd14** [comment]
@morganchen12 your commits say you updated for compatibility to Firebase 10, yet [Package.swift](https://github.com/firebase/geofire-objc/blob/v5.0.0/Package.swift#L20) shows it is still dependent on Firebase lower versions.

Do you have any updates on this?

**Comment by smaldd14** [comment]
For those that need it, I forked the repo and upgrade the version to be compatible with Firebase up to v11.0.0. This allowed me to submit my app to App store

https://github.com/smaldd14/geofire-objc

**Comment by kristjan97** [comment]
@morganchen12 is this repo dead?

**Comment by morganchen12** [comment]
Hey all. The outdated Firebase version is now fixed in v5.0.1. This repo doesn't have much active staffing, but its API is also fairly stable over time and doesn't tend to break when upstream Firebase updates. In the future feel free to make a PR and I'll review it and get it merged sooner.
