### ISSUE TITLE
dyld[3143]: Library not loaded: @rpath/GeoFire.framework/GeoFire

### ISSUE THREAD

**Issue by Bobbykart** [firebase/geofire-objc#167]
When i try to test my app i get this error: dyld[3143]: Library not loaded: @rpath/GeoFire.framework/GeoFire
  Referenced from: <66D6BC38-251B-33DA-AABE-9ED3D3A4E452>

**Comment by morganchen12** [comment]
You'll need to either copy GeoFire into the test bundle where `dyld` looks for libraries or add the existing location of GeoFire to your target's `Runpath Search Paths`. See Apple's docs for why you're getting this error: https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/RunpathDependentLibraries.html
