### ISSUE TITLE
download framework link for 1.1.2

### ISSUE THREAD

**Issue by pgherveou** [firebase/geofire-objc#19]
Hey guys could you add a link for the latest version?
this link exists 
https://github.com/firebase/geofire-objc/releases/download/v1.1.1/GeoFire.framework.zip

but not this one
https://github.com/firebase/geofire-objc/releases/download/v1.1.2/GeoFire.framework.zip

**Comment by jwngr** [comment]
The zip file has been added. Thanks for the heads up.
