### ISSUE TITLE
Transitive dependencies with Firebase 2.4.0

### ISSUE THREAD

**Issue by Bamsoo** [firebase/geofire-objc#21]
Hi there,

Since Firebase 2.4.0 release, installing GeoFire with cocoa pods (and `use_frameworks!`) leads to:
`[!] The 'Pods' target has transitive dependencies that include static binaries: (.../Firebase.framework)`

**Comment by mcdonamp** [comment]
Hey @Bamsoo, yep, we're looking into it! Looks like we're going to have to change some things up in our build system to ensure that transitive deps work properly.

**Comment by mcdonamp** [comment]
@Bamsoo Transitive dependency issues should be fixed in 2.4.1 (now on Cocoapods). Let me know if you've got any other problems.

**Comment by Bamsoo** [comment]
Perfect. Many thanks.
F.
