### ISSUE TITLE
Do Location Objects Have to be Stationary?

### ISSUE THREAD

**Issue by psopher** [firebase/geofire-objc#22]
Does GeoFire work for sharing current locations of multiple users (who are constantly moving around), or is it only useful for stationary objects (like the bars in your example)?

**Comment by puf** [comment]
The library tells you when an object entered or exited the area you're monitoring. So it can definitely be used to monitor moving objects. Read more about Geofire (and see some examples) here: https://www.firebase.com/blog/2014-06-23-geofire-two-point-oh.html
