### ISSUE TITLE
did not need bridging header file

### ISSUE THREAD

**Issue by rosscleung** [firebase/geofire-objc#24]
Thanks for geofire! It works like a charm!

I'm new to ios development and just figured out how to install framework and stuff. But I did not know how to create a bridging header file. I just downloaded and moved the GeoFire framework into my Swift xcode project, and I wrote "import GeoFire" in my .swift files and all the GeoFire functions work!

My question is, is this going to bite me in the butt later on by not creating a header file...? I tried to setLocation and getLocation functions and they all work perfectly onto my firebase database.

**Comment by jdimond** [comment]
It should not bite you later. If you were able to write import GeoFire, then your project is setup correctly and will compile and run just fine.
