### ISSUE TITLE
does not contain bitcode for  GeoFire.framework/GeoFire(GFGeoHash.o)

### ISSUE THREAD

**Issue by Imtayaz** [firebase/geofire-objc#26]
ld: '/App/Framework/GeoFire.framework/GeoFire(GFGeoHash.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jdimond** [comment]
It seems like GeoFire was not compiled to include bitcode. Since GeoFire is compiled from source there should be a setting to enable bitcode. Please ensure you are on the latest version of XCode, CocoaPods and all of you dependencies.

**Comment by Imtayaz** [comment]
I am using latest xcode and have complile code as per guideline still I have issue
