### ISSUE TITLE
Deadlock on @synchronize (self) in remove `removeObserverWithFirebaseHandle`

### ISSUE THREAD

**Issue by jcampbell05** [firebase/geofire-objc#31]
I am currently experiencing a deadlock using `removeObserverWithFirebaseHandle` on `@synchronize (self)`, any ideas what would cause this to happen ?

**Comment by jdimond** [comment]
It's the first we've heard about and maybe a bug in GeoFire. Do you have more info? A stack trace of the deadlocked threads or a way to reproduce?

**Comment by jcampbell05** [comment]
@jdimond seems like a compiler bug, a clean build fixed it.
