### ISSUE TITLE
Compile error when building the example project

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [firebase/geofire-objc#35]
Hi,

I'm trying to run the SFVehicles project inside the examples folder in a device. I'm using Xcode 7.3. When I build it, I get the error **'Firebase/Firebase.h' file not found**.

**Comment by jfrancop** [comment]
@Isuru-Nanayakkara did you get it to work?

I also wanted to run the example project, I pod installed firebase~>2.5 and GeoFire~>1.1 to make sure I wouldn't get problems with this 2year old source code. But I get; 

`clang:`` error: linker command failed with exit code 1 (use -v to see `invocation)`

Any ideas anyone?

**Comment by morganchen12** [comment]
Fixed in 4781cf005a3740cbe371507b8b09d08db4840088.
