### ISSUE TITLE
Firebase 3.0 requires GeoFire 1.2

### ISSUE THREAD

**Issue by mach** [firebase/geofire-objc#37]
Firebase 3.0 is now released and it requires GeoFire v1.2.
When will it be available?

**Comment by Mazorati** [comment]
+1

**Comment by X-Zibit** [comment]
+1

**Comment by trueangle** [comment]
+1

**Comment by peterdev2** [comment]
+1

**Comment by JamesRagnar** [comment]
+1

**Comment by jwngr** [comment]
Best estimate I can give you is that we will update GeoFire for iOS in the coming days to weeks. We've got a lot of open source libraries to update across a handful of languages, so it takes us time to make it all happen. Pull requests are always welcome if you want to give it a shot yourself!

You can use the PR for [GeoFire for JavaScript](https://github.com/firebase/geofire-js/pull/99) as a template.

**Comment by chrisze** [comment]
+1

**Comment by brendancallahan** [comment]
+1

**Comment by matthewswallace** [comment]
+100

**Comment by kdzapp** [comment]
+1

**Comment by reidsheppard** [comment]
+1000000

How is this not updated?

**Comment by gtchance** [comment]
+1

**Comment by gdovicak** [comment]
+1

**Comment by BeauNouvelle** [comment]
+ infinity + 1

**Comment by katowulf** [comment]
Hi Gents, we've given an estimate for the time frame of this update. Please keep the conversation constructive. The best way to speed up the process is with a well thought, well structured PR (new docs, new tests, and/or new code). Locking this thread so we don't have to burn time moderating uncivil behavior (again).

**Comment by mcdonamp** [comment]
Thanks to @HeyDaniel and PR #40, this will happen relatively soon. I think what he did was a great example of open source contribution, and I'd love to see others get involved solving issues in the same way 🔥

**Comment by mcdonamp** [comment]
Also thanks to @TimKreger-IA and #44, we'll be merging #45 tomorrow morning after which you can download the code and are good to go. We haven't decided if we want to wait to deploy to CocoaPods until the Java version is ready to deploy, or not, but at least people won't be blocked on needing new code :)

**Comment by mcdonamp** [comment]
Ok, we've merged #45 in, and will deploy to CocoaPods soon. That said, the code is in and you can include this project as source, and even ship it as such, so don't feel blocked!

I'll close this and we'll track the deployment separately.
