### ISSUE TITLE
I made a geofire version support Firebase 3.2.0

### ISSUE THREAD

**Issue by HeyDaniel** [firebase/geofire-objc#40]
download URL
https://drive.google.com/open?id=0B0tlPhDqk_j_a01NNTdraG0wVDg

**Comment by greggmojica** [comment]
@HeyDaniel Does this work in swift?

**Comment by HeyDaniel** [comment]
of course it work in swift

**Comment by mcdonamp** [comment]
Awesome, thanks for doing this! We'll review in #39 and merge it in when ready :)
