### ISSUE TITLE
How to update the query criteria?

### ISSUE THREAD

**Issue by Mazorati** [firebase/geofire-objc#41]
Hello! I want to update my existing GeoFire query criteria with different center location.
I documentation: "To update the query criteria you can use the center and radius properties on the GFQuery object. ". But there is no center and radius properties in GFQuery object (https://geofire-ios.firebaseapp.com/docs/Classes/GFQuery.html) ? How to solve this problem?

**Comment by jwngr** [comment]
I assume you found them [here](https://geofire-ios.firebaseapp.com/docs/Classes/GFCircleQuery.html.

**Comment by Mazorati** [comment]
@jwngr yes!
