### ISSUE TITLE
No such module 'GeoFire'

### ISSUE THREAD

**Issue by MidnightSwan** [firebase/geofire-objc#51]
I get the following error "No such module 'GeoFire'" when I try to use "import GeoFire" in swift. I have successfully installed GeoFire using the following:

pod 'Firebase'
pod 'Firebase/Database'
pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

There are no other issues in my code and it's fresh project. Has anyone else encountered or solved this issue?

**Comment by kianusharyan** [comment]
I am having the same problem. My podfile looks like this:

```
platform :ios, '9.0'
use_frameworks!

pod 'Firebase'
pod 'Firebase/Database'
pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

target 'HandShake' do

end
```

**Comment by mcdonamp** [comment]
Which version of CocoaPods are you using? We're seeing some differences between 0.39 and 1.0 in how they handle modules. In the short term, you can probably add a bridging header and do `#import <GeoFire/GeoFire.h>`, so you're using the header rather than the module.

@jdimond this might also mean that we need to add our own custom modulemap.

**Comment by MidnightSwan** [comment]
Please fix this or put up information on the README so that people don't have to dig around for solutions after their code fails. Speaking honestly as a developer who has used firebase for years, this reflects extremely poorly on what has been a very solid platform. Because GeoFire 2.0 doesn't work, developers who expected an easy transition to 2.0 are now left hanging with a half-baked product.

**Comment by kianusharyan** [comment]
Doing `gem which cocoapods` gave me 1.0.1

the #50 solution doesn't work for me either.

**Comment by mcdonamp** [comment]
@MidnightSwan totally hear you on this, and we're frustrated with this as well. We thought it would be an easy fix as well; unfortunately, given the transition from CP 0.39 to 1.0 (which seems to contribute to this issue), combined with a lot of work we did adding modulemaps and working on dynamifying static libs in Firebase 3.x, things collided very poorly.

dbb8d193f5ee1371837800d0502bd29cba779da4 adds information about this and asks folks to track #48.

@kianusharyan this is the behavior we're seeing as well--I assume it works for people using 0.39 (because it works for us when we use 0.39). `¯\_(ツ)_/¯`

**Comment by Filipetb** [comment]
Hey guys, after a long time trying to figure out this problem I finally solved. Here what I did:
1. Download the GeoFire 2.0 from  "https://github.com/firebase/geofire-objc.git"
2. Extract the zip
3. Put all files from API and Implementation folder together
4. Drag this files and drop in my project (I created a group for those files, just for organize)
5. Create the bridge that is suggested by Xcode
6. Put only #import "GeoFire.h" at in it
7. Fix the reference at GeoFire+Private.h putting #import "GeoFire.h" instead #import <GeoFire/GeoFire.h>

PS: My cocoapods version is 1.0.0
![captura de tela 2016-07-13 as 23 31 47](https://cloud.githubusercontent.com/assets/4166843/16826236/17ad61ba-4952-11e6-909e-4620305b71df.png)

**Comment by keegho** [comment]
#Guys these are the steps i took to implement Geofire. Im using xcode 8.

This is my podfile
 ```
platform :ios, '9.0'

target 'Firebasetest' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
end
```

Then i clicked on the FirebaseDatabse framework in the pods folder and on the right side i choose the file icon and in the targeting section list i choose Geofire.

Then in my project folder swift files i just `import Geofire`
And thats it.
This is how my project looks.
![screen shot 2016-09-24 at 12 43 52 pm](https://cloud.githubusercontent.com/assets/16656424/18807935/a0800b60-8254-11e6-9941-71f9092dc8c7.png)

**Comment by tzdesign** [comment]
@keegho you made my day man!

**Comment by keegho** [comment]
@tzdesign Your welcome have a happy coding day 📄

**Comment by netdawgx** [comment]
Hopefully this helps someone - I used a combination of the above solutions to fix my problem. This worked for me as of Oct 26, 2016 with a fully updated Cocoapods, XCode, Firebase, GeoFire.

I am using **CocoaPods version 1.1.1** and **XCode v 8.0 (8A218a)**

Here is my **Podfile**:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapZumi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapZumi
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
end
```

**### Step 1.** After installing the pods open up the xcworkspace file.

**### Step 2.** Navigate to GeoFire+Private.h and change `#import <GeoFire/GeoFire.h>` to `#import "GeoFire.h"` as shown in @Filipetb 's picture:
![image](https://cloud.githubusercontent.com/assets/1324957/19715882/6136bf18-9b26-11e6-84e1-0e59c5de5481.png)

**### Step 3.** Navigate to FirebaseDatabase.framework and check mark GeoFire as a target membership as shown in @keegho 's picture:
![image](https://cloud.githubusercontent.com/assets/1324957/19715909/887afef4-9b26-11e6-9cc1-d77931dabcb8.png)

Everything should be working now, **be aware that running pod update or pod install will reset these changes and they will need to be implemented again.**

**Comment by Rydeyabike** [comment]
@netdawgx I've tried your solution, and every other solution/trick I could find, with no luck. Thanks for the detailed attempt (glad it worked for you), any ideas what I am doing wrong or what I should try next. 

I am running XCode 8.0, CocoaPods 1.1.1, here is my podfile:

`platform :ios, '9.0'

target 'Fyre' do
  use_frameworks!

    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'

    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'

    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

end
`
And have followed your steps:
![screen shot 2016-12-07 at 2 42 38 pm](https://cloud.githubusercontent.com/assets/16723372/20983714/829cb49c-bc8b-11e6-9ee0-b8127bcc4db1.png)

![screen shot 2016-12-07 at 2 43 55 pm](https://cloud.githubusercontent.com/assets/16723372/20983745/a04043a6-bc8b-11e6-813f-cff187515ca2.png)

I also tried adding these lines to my podfile, no luck:
`post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "GeoFire"
            target.build_configurations.each do |config|
                config.build_settings["FRAMEWORK_SEARCH_PATHS"] = '$(inherited) "${SRCROOT}/FirebaseDatabase/Frameworks"'
                config.build_settings["HEADER_SEARCH_PATHS"] = '$(inherited) "${PODS_ROOT}/Headers/Public/FirebaseDatabase"'
                config.build_settings["OTHER_CFLAGS"] = '$(inherited) -isystem "${PODS_ROOT}/Headers/Public/FirebaseDatabase"'
                config.build_settings["OTHER_LDFLAGS"] = '$(inherited) -framework "FirebaseDatabase"'
            end
        end
    end
end
`

I've tried it with and without a bridging header. Either way seemed to make no difference, I got the same error and no new errors.

One difference I noticed was that your GeoFire folder is under a folder called Helpers where you also  store your bridging header. For me cocoapods installs my Geofire folder under the pods project folder. Could this maybe make a difference with regards to a bridging header? And if so how would I go about moving it to the proper place (presumably my project as apposed to the pods project)?

I have tried making this move but that seems to mess up a whole bunch of other things. Namely the paths XCode expects to find GeoFire at. And it does nothing to solve my original problem.

Any advice/help from anyone would be GREATLY appreciated. Thanks in advance!

**Comment by jdleo** [comment]
As with any pod that doesn't work (seems to be a common issue), usually a surefire way to fix it is going to scheme, edit scheme and set the target to the library that isn't working, then just hit Build. then switch back to your main project in scheme, and run again. you'll see the error wont be there

**Comment by aietsg** [comment]
I have selected GeoFire for Target Membership from  Pods->Pods->FirebaseDatabase->Frameworks->FirebaseDatabase.framework, alter GeoFire+Private.h to #import "GeoFire.h”, and include #import "GeoFire.h" in my bridging header. I get the pod from src pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git’. Yet I still get then “No such module ‘GeoFire’ error, which prevents me from building unlike @netdawgx. I am running XCode 8.3 with Swift 3. Anyone else had this problem?

**Comment by jonahbron** [comment]
After a lot of following more complicated instructions, I was able to get it working for my Swift application with the following subset of steps:

1. Add `pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'` to Podfile
2. Run `pod install`
3. Click on Pods > Pods > FirebaseDatabase > Frameworks > FirebaseDatabase.framework, and in the File Inspector, check "GeoFire" under Target Memberships
![screen shot 2018-01-07 at 10 21 48 am](https://user-images.githubusercontent.com/607976/34652547-ad21d58a-f394-11e7-9c71-b89a51818a23.png)
4. Product menu > Build

And now I can add `import GeoFire to my application files.

**Comment by mcdonamp** [comment]
Would you mind trying the standard `GeoFire` pod with CocoaPods 1.4? You can install it via: `sudo gem install cocoapods --pre`

**Comment by ghowen** [comment]
Seems that this does not work anymore with Firebase 5.0.0 as they have switched to source pods. Any idea on how to install now? Until I figure this out my complete project is broken as pod updates do not work anymore (see #114).

**Comment by ghowen** [comment]
@MujiWolf Please see https://github.com/firebase/geofire-objc/issues/114. It should be fixed. Maybe cleaning the project and build folders helps? It's been working for me since the referenced fix.
