### ISSUE TITLE
regionQuery - key Exit doesnt work?

### ISSUE THREAD

**Issue by werneroi** [firebase/geofire-objc#53]
I have a geofire setup.
The Region enter event works fine.
how ever the Region exit never returns anything.

Maybe someone knows why????

`
override func observeValueForKeyPath(keyPath: String?, ofObject object: AnyObject?, change: [String : AnyObject]?, context: UnsafeMutablePointer<Void>)
    {
        print ("recieved update - key changed")
                
        if (self.mapView.showsUserLocation && self.mapView.userLocation.location != nil)
        {            
            let span = MKCoordinateSpanMake(0.0125, 0.0125)
            let region = MKCoordinateRegion(center: self.mapView.userLocation.location!.coordinate, span: span)
            self.mapView.setRegion(region, animated: true)            
            let location = mapView.userLocation.location
            
            if regionQuery == nil {
            let hostGeoFire  = GeoFire(firebaseRef: self.ref.child("geo").child("hosts"))
            regionQuery = hostGeoFire?.queryWithRegion(region)
        
            regionQuery!.observeEventType(GFEventType.KeyEntered, withBlock: { (key: String!, location: CLLocation!) in                
                print("found a reqionKey: ",key)
                        }) 
                        { (error) in
                            print(error.localizedDescription)
                    }
                })
                
                regionQuery!.observeEventType(GFEventType.KeyExited, withBlock: { (key: String!, location: CLLocation!) -> Void in                    
                    print ("I am leaving this host")
                })                
            }
                            
//            // Query with an extremely limited span.
            if foundQuery == nil
            {
                foundQuery = geofire?.queryAtLocation(self.mapView.userLocation.location, withRadius: 0.1)                
                foundQuery!.observeEventType(GFEventType.KeyEntered, withBlock: { (key: String!, location: CLLocation!) -> Void in                    
                        print ("THIS IS what i get", key)
                })
                foundQuery!.observeEventType(GFEventType.KeyExited, withBlock: { (key: String!, location: CLLocation!) -> Void in                    
                    print ("User Exit", key)
                })   
            } else
            {
                foundQuery?.center = self.mapView.userLocation.location
            }        
        }
    }
`

**Comment by jdimond** [comment]
Key exited will be called if a key is deleted, moves out of the query or the query is updated to a different region that no longer contains the key. If this is a bug please provide a minimal repro (including how the data looks like and what steps are necessary that should cause a key-exited event, but doesn't) and re-open this issue.

**Comment by werneroi** [comment]
Hi, so here is how to recreate the bug...
Assuming you have Firebase set up already of course, just: 
1. download UIViewController.swift and import it (or copy) to your project.
2. add a map view and a button to the View.
3. connect the button to the setupHost  IBAction at the end of the code.
4. run the app
5. choose a location - e.g "Apple"
6. click the button, it will set up a value both in Firebase data and as Geo location.
7. you should get a "region found" print with the unique number it created in the console.
8. move to another location (e.g custom or Free drive)
9. **no exit message arrives...**
10. if you go back to the Apple location it will show a found region statement again.

at least.. this is what happens here. I think it is a bug :(


[ViewController.swift.zip](https://github.com/firebase/geofire-objc/files/332856/ViewController.swift.zip)

**Comment by jdimond** [comment]
Thanks for getting back with a reproducible test case. It seems like it's actually correct that KeyExited is never fired

1. Every time you update the query, you actually create a **new** query, leaving the old one still active:<br/>
    `regionQuery = geofire?.queryWithRegion(region)`<br/>
   If you want to keep the query updating, you will need to actually update the query:<br/>
   `regionQuery.region = region`
2. Every time you update the host in `setupHost` you create a new reference:
   `let uniqueHostRefNumber = self.hostsRef.childByAutoId()`
   So you will never actually override an old location, so old values will always stick around and never leave the query.

So it seems this is not actually a bug in GeoFire.
