### ISSUE TITLE
no exit statement for regionQuery 

### ISSUE THREAD

**Issue by werneroi** [firebase/geofire-objc#54]
Hi, sorry I dont know how to reopen a case, so I had to post a new one.

Here is how to recreate the bug.

Assuming you have Firebase set up already of course: 
1. download UIViewController.swift and import it (or copy) to your project.
2. add a map view and a button to the View.
3. connect the button to the setupHost IBAction at the end of the code.
4. run the app
5. choose a location - e.g "Apple"
6. click the button, it will set up a value both in Firebase data and as Geo location.
7. you should get a "region found" print with the unique number it created in the console.
8. move to another location (e.g custom or Free drive)
9. no exit message arrives...
10. if you go back to the Apple location it will show a found region statement again.

at least.. this is what happens here. I think it is a bug :(
[ViewController.swift.zip](https://github.com/firebase/geofire-objc/files/332858/ViewController.swift.zip)

**Comment by jwngr** [comment]
I re-opened #53, so I'm closing this duplicate.
