### ISSUE TITLE
Updating center & radius in GFCircleQuery doesn't do anything

### ISSUE THREAD

**Issue by lgaryfallos** [firebase/geofire-objc#56]
Hi,

I setup my circle query like so
`circleQuery = geoFire.queryAtLocation(currentLocation, withRadius: radius)`

Then on a location listener I change the center:
`circleQuery.center = currentLocation`

And when the user changes the query radius:
`circleQuery.radius = newRadius`

My problem is that, I never get keyEntered or keyExited events when I change the radius.
If I kill the app and restart it, the keyEntered events get fired since the radius is stored in user defaults, so the next time circleQuery is created it gets the new value.

I declare these
```
let geoFire = GeoFire(firebaseRef: ref.child("locs"))  
var circleQuery: GFCircleQuery!

```

I'm starting the circle query:
```
LocationManager.shared.observeLocations(.Block, frequency: .OneShot, onSuccess: { location in
        currentLocation = location
        if circleQuery != nil {
            circleQuery.radius = radius
            circleQuery.center = currentLocation
            debugPrint("got ONESHOT location and UPDATING query objects")
        } else {
            debugPrint("got ONESHOT location and --CREATING-- query objects")
            circleQuery = geoFire.queryAtLocation(currentLocation, withRadius: radius) 
        }
    }) { error in
        debugPrint(error.description)
    }

```

And then I have these:
```
//remove post if far away from us
    circleQuery.observeEventType(.KeyExited, withBlock: { (key: String!, location: CLLocation!) in
        debugPrint("\(key) exited search area, remove from tableview")
        stopMonitoringKey(key)        
    })
    
    circleQuery.observeEventType(.KeyEntered, withBlock: { (key: String!, location: CLLocation!) in
        print("------------> \(key) entered the search area and ")
        UIApplication.sharedApplication().networkActivityIndicatorVisible = true
        monitorLostDataForKey(key) //start monitoring key values
    }) 
```

Am I missing something?

This is in Xcode 7.3.1 with these versions for geofire/firebase: 

> Using Firebase (3.2.1)
> Using FirebaseAnalytics (3.2.0)
> Using FirebaseAuth (3.0.2)
> Using FirebaseDatabase (3.0.1)
> Using FirebaseInstanceID (1.0.6)
> Using FirebaseStorage (1.0.1)
> Using GeoFire (2.0.0)

**Comment by jwngr** [comment]
I think Jonny's answer [here](https://github.com/firebase/geofire-objc/issues/53#issuecomment-228832478) may help you. Let us know if that's your issue.

**Comment by lgaryfallos** [comment]
Well, you were right!

I read that, and was pretty certain I wasn't recreating the query, but it seems like I was, I changed it and it's working as it should, events firing and everything.

Thanks!

**Comment by almehf** [comment]
@lgaryfallos  how did you figure it out?

**Comment by lgaryfallos** [comment]
@almehf it's been a while but I think I ended up creating a singleton instance of everything I needed that had to do with geo queries. That made certain that I only had one circle query object at any time.

**Comment by almehf** [comment]
@lgaryfallos I'm working on an app similar to "Letgo" where i need to filter items based on location.. Any tips or resources you recommend? 
Thank you in advance!

**Comment by lgaryfallos** [comment]
@almehf not anything more than firebase with geofire. I just monitor the user's location for significant changes and update my center and re-arrange the listeners for the returned keys.

 Firebase ended up being a bit restrictive for my use case, and I could have done the same geo query part (which is really fast and hassle free) with geo fire but instead of firebase keys I could index mysql IDs. Well next time I guess.

**Comment by almehf** [comment]
Isn't more efficient to monitor the user's posts for changes instead of user's location?  I believe the user doesn't rest in one location unlike the post.. It certainty will be stored at that specif location,

**Comment by lgaryfallos** [comment]
@almehf I don't know what your use case is. In mine, I had multiple user posts from multiple locations (not always the actual user's location), and I wanted to show to the user posts around him/her, so it made sense to index/store the post's location and then query using the current user's location as the center.

**Comment by almehf** [comment]
I see what you did there. Thanks for the help. Are you ever planning to post a sample of that project into github?

**Comment by lgaryfallos** [comment]
I doubt it, since it was my first ever swift project and I'm certain it's not code for the public eye :/

If I ever get around to cleaning up/rewrite parts of it, I'll definitely upload it, but don't hold your breath just yet :)

**Comment by almehf** [comment]
I won't lol Thanks though for your time. Much appreciated.
