### ISSUE TITLE
GFquery to FirebaseTableViewDataSource 

### ISSUE THREAD

**Issue by kmb266** [firebase/geofire-objc#58]
It would be incredible if there was a simple way to map from a geofire query result to a FirebaseDatabase query so that the FirebaseTableViewDataSource could populate. I think it would be great (because geofire writes to its own section of the database) if there was a way to make the object keys from a corresponding geofire query populate directly into a FIrebaseUI tableview through the FirebaseTableViewDataSource. I do not think this is already available because i have been working with this for a couple days and scouring the internet and have given up on a module that is already written, and I just wrote my own.

Am I missing something? is this a possibility in the future?

**Comment by morganchen12** [comment]
This is not something we're looking at adding in the near future, but if there's more requests for it, I'll take a look.
