### ISSUE TITLE
Ordering geofire results by distance

### ISSUE THREAD

**Issue by raulrom13** [firebase/geofire-objc#59]
Hi,

I'm doing some test with GFCircleQuery and the results are inside the circle but my app doesn't get keys ordered by distance. I don't understand this order filter.

Can someone explain me how it works?

Thank you.

**Comment by jwngr** [comment]
There is no real ordering. For all intents and purposes, you can assume the ordering is random. If you are looking to get the closest N items to a location, see https://github.com/firebase/geofire-js/issues/59#issuecomment-70350560 for two potentially ways to do this.

**Comment by srujanb** [comment]
I read somewhere that in geofire for JavaScript the geoquery result is ordered by distance, so can you please confirm if that was a wrong statement or geoquery results are dependent on whether you're using it from Android or iOS or web?

**Comment by morganchen12** [comment]
Geoquery result ordering shouldn't change based on what platform you're querying from. You shouldn't assume strict ordering by distance.

**Comment by srujanb** [comment]
Well, I would like to get some confirmation on this as things contradict with the posts here:
https://groups.google.com/d/msg/firebase-talk/LT5zsYcAFK8/paK8b7bhYegJ
and 
https://groups.google.com/d/msg/firebase-talk/LT5zsYcAFK8/WoGnnKIu6CgJ
and
https://stackoverflow.com/a/40998332/2649104
Or it is just a coincidence that they are getting results based on ascending order of distance?

**Comment by morganchen12** [comment]
Sorry, I worded my last comment poorly. [Jonny's comment](https://groups.google.com/d/msg/firebase-talk/LT5zsYcAFK8/fuTDtRt2cKgJ) in the thread you linked talks about this in more detail. The ordering of the Geoquery results is dependent on the results of the RTDB queries the library is performing internally, which are not guaranteed to return consistently ordered results.
