### ISSUE TITLE
Locations with identical coordinates

### ISSUE THREAD

**Issue by edc1591** [firebase/geofire-objc#62]
I've added locations with identical lat/long coordinates to my database, but when I query I'm only getting the most recent one back. Is this the expected behavior?

I'm using GeoFire 2 and Firebase 3

**Comment by edc1591** [comment]
After some more testing, I've noticed that it happens even if the coordinates are not identical. For example, 40.759212,-73.984639 and 40.759211,-73.984638 are stored under the same key by GeoFire and only one is returned in my query.

**Comment by jdimond** [comment]
How are you setting the location? Do you mind copying the data after writing both locations?

**Comment by edc1591** [comment]
Not sure I understand. I'm setting the location using `GeoFire.setLocation`.

**Comment by jdimond** [comment]
Can you paste the code snippet here and paste the data from the Firebase dashboard after running the code?

**Comment by edc1591** [comment]
```
self.geoFire.setLocation(location, forKey: key) { error in
    if let error = error {
        observer.sendFailed(error)
    } else {
        observer.sendNext(location)
        observer.sendCompleted()
    }
}
```

`location` is a `CLLocation` object that is returned by `CLLocationManager` and `key` is the ID of another object stored elsewhere in my Firebase database.

`self.geoFire` is define as follows 
```
self.geoFire = GeoFire(firebaseRef: FIRDatabase.database().referenceWithPath(Path.Database.Locations.rawValue))
```

`Path.Database.Locations.rawValue` is just `"locations"`

Here's what the data looks like in Firebase. Two locations have identical coordinates and one has very similar coordinates. GeoFire assigns all three the same `g` value.

<img width="280" alt="screen shot 2016-09-08 at 1 32 19 pm" src="https://cloud.githubusercontent.com/assets/706048/18359620/b177ad1c-75c8-11e6-9915-ed85b33027af.png">

Apologies for the cut off longitude values, they're 8, 8 and 9.

**Comment by jdimond** [comment]
Can you clarify how you are querying? Despite having the same location, a query around (40.7..., -74.9...) should return all three results. The hash is only approximate to a couple cm's, so they might end up the same but that should not affect the query.

**Comment by edc1591** [comment]
I'm doing this:
```
let query = self.geoFire.queryWithRegion(region)
            
let handle = query.observeEventType(.KeyEntered) { (key, location) in
    observer.sendNext(key)
    observer.sendCompleted()
}
```

where `region` is:
```
▿ MKCoordinateRegion
  ▿ center : CLLocationCoordinate2D
    - latitude : 40.759211000000008
    - longitude : -73.984638000000004 { ... }
  ▿ span : MKCoordinateSpan
    - latitudeDelta : 0.01943898291469992 { ... }
    - longitudeDelta : 0.016093255609462176 { ... }
```

**Comment by edc1591** [comment]
This may be a bug in my code. I'm investigating.

**Comment by edc1591** [comment]
Yup, turns out it was a bug in my code. I was assuming that `observeEventType` would send a value for each matching location when it's actually sending a single dictionary containing all the matching locations.

Apologies for the false alarm and thanks for the help!
