### ISSUE TITLE
No results being returned for Geofire circle query

### ISSUE THREAD

**Issue by DuncanACampbell** [firebase/geofire-objc#66]
I'm not getting any results returned for a circle query and not sure what I'm doing wrong. Can anyone help?  I'm receiving the "ready" block but not receiving any "keyEntered" data.

I need to get a list of all events, which have a location in the region.  So this query should return one "event" = "mondayrun".

I'm using this code:

    GeoFire *geoFire = [[GeoFire alloc] initWithFirebaseRef:[_ref child:@"events"]];
    
    CLLocation *center = [[CLLocation alloc] initWithLatitude:37.7853889 longitude:-122.4056973];
    GFCircleQuery *circleQuery = [geoFire queryAtLocation:center withRadius:20];
    
    [circleQuery observeEventType:GFEventTypeKeyEntered withBlock:^(NSString *key, CLLocation *location) {
        NSLog(@"Key '%@' entered the search area and is at location '%@'", key, location);
    }];
    
    [circleQuery observeReadyWithBlock:^{
        NSLog(@"All initial data has been loaded and events have been fired!");
        block(nil, nil);
    }];`

And in my database I have an events collection, with a single object, located at those exact coordinates.
<img width="379" alt="screen shot 2016-11-27 at 13 48 53" src="https://cloud.githubusercontent.com/assets/698853/20648472/50b9d45e-b4a8-11e6-964e-321593a8d601.png">

Any ideas what I'm doing wrong?  Thank you!

**Comment by DuncanACampbell** [comment]
If I change the first line of the code to:
    GeoFire *geoFire = [[GeoFire alloc] initWithFirebaseRef:[_ref child:@"events/mondayrun"]];

it returns my object, but I need to get all the different run objects directly under "events".

**Comment by jwngr** [comment]
How are you adding data to your GeoFire index? Your data structure in the Firebase Realtime Database looks incorrect. Make sure you are using the latest version of the GeoFire library. Also, please share the code you used to add the data to your GeoFire index.

**Comment by paujur** [comment]
I'm having the exact same issue, and my data structure looks exactly the same...

**Comment by martpadmat** [comment]
I am also looking for the answer. I am unable to retrieve the data with GeoFire search query.

**Comment by DuncanACampbell** [comment]
Hi guys.  We solved the problem.  I hope this helps in some way.

**The short answer is to normalise the location data so that it is at the base of the data hierarchy**

In my example, the location object (created by Geofire) is located under the mondayRun object.  However, you need all the location objects at the base of the tree so that the GeoFire circleQuery can access all of them.

Structure your data like this - with each location having a unique key that matches the element it relates to in the data structure.  In the example, below you can see that our first location has a key of "team_-KbG2mHmbaQZzUDdNekv" which matches the key of the team entity which it relates to.

<img width="637" alt="screen shot 2017-02-02 at 11 46 08" src="https://cloud.githubusercontent.com/assets/698853/22546413/45aaa588-e93d-11e6-8c8f-039024026acc.png">

Then perform the GeoFire query to observe for matching locations.  As each location returns, you can then use Firebase to get the info about the entity (in out case, "team_-KbG2mHmbaQZzUDdNekv").

Let me know if any of that doesn't make sense.

@martpadmat @paujur
