### ISSUE TITLE
Trouble building projects with GeoFire pod in Swift 3/Xcode 8 

### ISSUE THREAD

**Issue by tiagoguy** [firebase/geofire-objc#68]
I've been having trouble with the GeoFire pod in several Xcode 8/Swift 3 projects.

Building these projects often gets me an Apple Mach-O Linker error (Framework not found GoogleToolboxForMac), and in one particular project a "Lexical or Preprocessor Issue" ('FirebaseDatabase/FirebaseDatabase.h' file not found).

I've tried creating new projects from scratch with just the GeoFire pod, but the Linker error persists.

Not sure what I could be doing wrong...

**Comment by danielroy** [comment]
I've had this happen when I included **use_frameworks!** in my Podfile for another framework I was trying to use.  Once I removed **use_frameworks!** and the related framework from the Podfile, the error you reported disappeared.

**Comment by woolardjason** [comment]
@tiagoguy Ever figure out a fix/work-around? I'm also getting the "('FirebaseDatabase/FirebaseDatabase.h' file not found)" when attempting to build.

**Comment by septronic2** [comment]
I had the same issue, and I ended up using the non-compiled version. I had to change the imports to reflect this though (use the name of the file instead of framework reference to that file)

**Comment by kumareshsaran** [comment]
Hello guys i got the same error in <Firebasedatabase/FirebaseDatebase.h> is not found.but the file geofire file is there in my project.i install and update the the pod but the still the the error is showing.i don't know how to slove this issuse.

**Comment by mcdonamp** [comment]
I'm going to chalk this up to #48 as well (transitive deps on static binaries, etc.). Re-open if I'm wrong.
