### ISSUE TITLE
_OBJC_CLASS_$_GeoFire

### ISSUE THREAD

**Issue by yanctrindade** [firebase/geofire-objc#69]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GeoFire", referenced from:
      objc-class-ref in MapViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

After Copied All Geofire Files to My Project and linked with bridgde-Header file this message keep coming when I try to run. Im updating my project from old firebase to new one with swift 3.0

**Comment by Carmen0821** [comment]
I am getting the same error through. Have you found any solution for it?

**Comment by brokenseal** [comment]
Same here.

**Comment by yanctrindade** [comment]
Can you guys remember me who it was happenning ?

I solved it some months ago. Now I am using geofire on pods.

**Comment by brokenseal** [comment]
@yanctrindade are you using GeoFire version 2 on pods? If so, can you please share the needed configuration? I was not able to installe GeoFire 2, no matter what I'm doing.

I'm now stuck having this same issue with "Undefined symbols for architecture arm64:" after having tried to install GeoFire by using a bridging header.

**Comment by brokenseal** [comment]
Quick update: @yanctrindade you inspired me to actually try again and install it using just CocoaPod and apparently it works!

This is the line I added: `pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git', :branch => 'mpmcdonald-use-community'`

I hope this will be helpful for somebody else as well.

By the way, if you have solved your problem, you should close this issue, possibly stating how :)
