### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by mikrobi** [firebase/geofire-objc#7]
Are you planning to publish GeoFire on http://cocoapods.org?

**Comment by steffenfrost** [comment]
Any progress on getting GeoFire on Cocoapods?

**Comment by jwngr** [comment]
Hey @steffenfrost - I'll check in with the guy who handles this stuff tomorrow and let you know what he says. I just think this task fell off our radar, but there's no reason why we can't put this on Cocoapods. Thanks for the reminder!

**Comment by jwngr** [comment]
GeoFire is [now available on CocoaPods](http://cocoapods.org/?q=geofire). Let us know if you run into any issues!

**Comment by mikrobi** [comment]
Awesome!
