### ISSUE TITLE
I can not use geofire Swift 3 / xCode 8

### ISSUE THREAD

**Issue by alextomas** [firebase/geofire-objc#73]
I've tried everything

![at-captura 2017-01-12 a las 11 10 18](https://cloud.githubusercontent.com/assets/2083214/21885402/c6ffdbd0-d8b7-11e6-91be-c7df2f0cc999.png)

My Podfile:

`#Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GeoFire' do
  #Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #Pods for GeoFire

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

end`

Help me please !

**Comment by tommybananas** [comment]
Have you set up a bridging header as seen here? 
https://github.com/firebase/geofire-objc/issues/48#issuecomment-225471707

**Comment by deborahelizabethpadilla** [comment]
Did you ever figure this out? Sometimes when I do not update my commits through Xcode, it tells me there is no such module and doesn't work properly. I've found that this is a bug with the beta version at least.

**Comment by aietsg** [comment]
bump

**Comment by almehf** [comment]
bridging header would fix the problem. Importing Geofire as a library wouldn't work.
