### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by dpstart** [firebase/geofire-objc#75]
I'm trying to use Geofire on Xcode 8.2/Swift 3.

I've imported the framework and added the bridging header.

Problem is, when I declare 

`var geoFire : GeoFire!`
 `var geoFireRef : FIRDatabaseReference!`

 I get this error: 

> Command failed due to signal: Segmentation fault: 11

**Comment by mcdonamp** [comment]
If I recall correctly (as this was months ago), this was an issue with the Swift compiler that has since been fixed. Are you still seeing this issue after upgrading to the latest version of XCode and Swift?
