### ISSUE TITLE
Cannot install from cocoapod

### ISSUE THREAD

**Issue by aizcheryz** [firebase/geofire-objc#76]
Hi, i've install firebase via cocoapods
![screen shot 2017-02-10 at 4 58 13 pm](https://cloud.githubusercontent.com/assets/3115658/22822512/59df8a02-efb2-11e6-9187-bed64afdc956.png)
then i install GeoFire and error like this
![screen shot 2017-02-10 at 4 58 55 pm](https://cloud.githubusercontent.com/assets/3115658/22822526/6b13165e-efb2-11e6-9379-686c7a7cc5d6.png)
How to fix it? Thanks

**Comment by jsmvalente** [comment]
https://github.com/firebase/geofire-objc/issues/48#issuecomment-225471707
