### ISSUE TITLE
Is Geofire going to be updated - or is it end of life?

### ISSUE THREAD

**Issue by grantkemp** [firebase/geofire-objc#80]
Hi - it would be great to get some certainty about what the future of Geofire will be - will it be updated /replaced or just left alone  to disappear. 
I noticed that there are a lot of pull requests that are unanswered and a lot of issues which are pending.  
If it won't be continued- then it would be useful to know as potentially as a community we can build a replacement for this amazing library

**Comment by felixchan** [comment]
Ditto

**Comment by ralcr** [comment]
Amazing library that does not work...
Mine can't import FirebaseDatabase

**Comment by grantkemp** [comment]
@ralcr  that part does work for me.  Why don't you remove your comment above and open a ticket on stackoverflow so we can help.  Lets keep this ticket  on the topic of getting an update.

**Comment by donpironet** [comment]
+1

**Comment by mcdonamp** [comment]
See #95, we're rejiggering dependencies to make it easier to work with/on.

**Comment by morganchen12** [comment]
We're going to continue supporting this library, though new feature development is not a priority for us. Please file any new issues you run into and feel free to submit pull requests.

I'll be going through the backlog of issues and PRs over the next two weeks or so.
