### ISSUE TITLE
Firebase iOS SDK (v4.0.0) Support

### ISSUE THREAD

**Issue by zgosalvez** [firebase/geofire-objc#85]
I am unable to install the latest SDK due to dependency requirements of GeoFire. Here's the error message produced when attempting to install with CocoaPods.

```bash
[!] Unable to satisfy the following requirements:

- `Firebase/Database` required by `Podfile`
- `Firebase/Database (~> 3.2)` required by `GeoFire (2.0.0)`

Specs satisfying the `Firebase/Database, Firebase/Database (~> 3.2)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by eliwhittle** [comment]
I am getting the same error after adding Geofire to my podfile running `pod install`, this happened after updating Firebase to the latest version 4.0.0.

```
[!] Unable to satisfy the following requirements:

- `Firebase/Database` required by `Podfile`
- `Firebase/Database (= 4.0.0)` required by `Podfile.lock`
- `Firebase/Database (~> 3.2)` required by `GeoFire (2.0.0)`
```

**Comment by simonbengtsson** [comment]
One fix before the podspec is updated is to simply drop the source files of geofire into your project instead of having geofire managed by cocoa pods.

**Comment by jdimond** [comment]
This should be fixed, let me know if you are still seeing this issue.

**Comment by zgosalvez** [comment]
Fix confirmed. Thank you so much @jdimond !
