### ISSUE TITLE
Exception Raised on Line 34 in GFGeoHash.

### ISSUE THREAD

**Issue by sachinvas** [firebase/geofire-objc#88]
So, the problem stems from + (NSSet *)queriesForRegion:(MKCoordinateRegion)region of GFGeoHashQuery. 

The [GFGeoHashQuery bitsForRegion:region] can return a value greater than of 106.

Hence the value of the geoHashPrecision will be greater than 22. This causes the exception to be raised. Is this intended or can we have a defensive checks.

**Comment by maximkhatskevich** [comment]
This happens to me when I use RegionQuery (in a Swift 4 project) with at least one observer registered. If it's a CircleQuery - this exception does not occur.

**Comment by morganchen12** [comment]
Can you share a stack trace and/or repro?

**Comment by morganchen12** [comment]
Closing since I wasn't able to repro this issue.
