### ISSUE TITLE
Can't stop observing

### ISSUE THREAD

**Issue by psyh** [firebase/geofire-objc#90]
I'm using GeoFire and trying to fetch only 3 results that satisfy some conditions. This it my case and it doesn't stop observer. There are several thousands results and I get it all but I need only 3 and stop.  
Please can somebody help? Thanks.

```
var newRefHandle: FIRDatabaseHandle?
var gFCircleQuery: GFCircleQuery?

func findFUsersInOnePath(location: CLLocation,
                         radius: Int,
                         indexPath: String,
                         completion: @escaping () -> ()){
    var ids = 0
    let geofireRef = usersRef.child(indexPath)
    if let geoFire = GeoFire(firebaseRef: geofireRef) {
        gFCircleQuery = geoFire.query(at: location, withRadius: Double(radius))
        newRefHandle = gFCircleQuery?.observe(.keyEntered, with: { (key, location) in
            // if key fit some condition
            ids += 1
            if (ids >= 3) {
                self.gFCircleQuery?.removeObserver(withFirebaseHandle: self.newRefHandle!)
                completion()
            }
        })

        gFCircleQuery?.observeReady({
            completion()
        })
}
```
removeAllObservers - is also not working

**Comment by jesster2k10** [comment]
I've got the exact same issue. It seems like this project may be dead. I'm going to try look for a solution

**Comment by psyh** [comment]
I've got my [answer](https://stackoverflow.com/a/45180086/2831157). There is no any solution except accepting the fact it works as it. So we should think different when we use Geofire.
