### ISSUE TITLE
2 compiler warnings (Documentation issue) in Xcode 9 / Swift 4 project

### ISSUE THREAD

**Issue by ghowen** [firebase/geofire-objc#98]
Pods/GeoFire/GeoFire/API/GeoFire.h:108:11: Empty paragraph passed to '@return' command

Pods/GeoFire/GeoFire/API/GeoFire.h:108:5: '@return' command used in a comment that is attached to a method returning void

**Comment by moazkh60** [comment]
I am facing the same issue. Geofire team Please resolve this issue at the earliest.

**Comment by ghowen** [comment]
Got one more (semantic issue):

Pods/GeoFire/GeoFire/API/GFQuery.h:43:30: This block declaration is not a prototype

**Comment by brokenseal** [comment]
Is this project actually maintained? No reply in more than a month to a fairly pressing issue, that is a bad sign...

**Comment by SaifSideDev** [comment]
@mcdonamp Hey, GeoFire seems great. Any ETA on when GeoFire pods will be ready to use with Swift 4 and Firebase 4 Xcode projects?

**Comment by brokenseal** [comment]
@SaifSideDev I am using it with a Swift 4 project

**Comment by SaifSideDev** [comment]
@brokenseal That's awesome. I figured it out too. Are you using the Firebase Community pods? That's how I got it to work for anyone who is wondering?

**Comment by SaifSideDev** [comment]
@brokenseal That's awesome. I figured it out too. Are you using the Firebase Community pods? That's how I got it to work for anyone who is wondering.

**Comment by doovers** [comment]
@SaifSideDev I used this workaround with the normal Firebase pods and it works fine too:

```
# GeoFire workaround
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'GeoFire' then
            target.build_configurations.each do |config|
                config.build_settings['FRAMEWORK_SEARCH_PATHS'] = "#{config.build_settings['FRAMEWORK_SEARCH_PATHS']} ${PODS_ROOT}/FirebaseDatabase/Frameworks/ $PODS_CONFIGURATION_BUILD_DIR/GoogleToolboxForMac $PODS_CONFIGURATION_BUILD_DIR/nanopb $PODS_CONFIGURATION_BUILD_DIR/leveldb-library"
                config.build_settings['OTHER_LDFLAGS'] = "#{config.build_settings['OTHER_LDFLAGS']} -framework FirebaseDatabase"
            end
        end
    end
end
```

**Comment by morganchen12** [comment]
These should be fixed in master; please re-open if they aren't.
